import { app, dialog, ipcMain, shell } from 'electron'
import { promises as fs } from 'node:fs'
import { join } from 'node:path'
import type {
  AppInfo,
  BackupRecord,
  ChatSkillsState,
  DetectionResult,
  InstallPlan,
  OperationResult
} from '@shared/types'
import { CHANNELS } from '@shared/channels'
import { CATEGORIES, COMPONENTS, recommendedComponentIds } from '../core/catalog'
import { listBackups } from '../core/backup'
import { buildDiagnosticReport } from '../core/diagnostics'
import { scanSystem } from '../core/detect'
import { appStateDir, claudeHome, realEnv } from '../core/env'
import type { Env } from '../core/env'
import { chooseInstallRoute, describeRoute, installClaudeCode } from '../core/claude-code-install'
import {
  buildChatPackages,
  chatPackageDir,
  chatSkillIdsFor,
  clearChatSetup,
  confirmChatSetup,
  readChatSkillsState
} from '../core/chat-skills'
import {
  buildPlan,
  installComponents,
  removeComponents,
  restoreFromBackup
} from '../core/installer'
import { loadManifest } from '../core/manifest'
import { log } from '../core/logger'
import { openExternalIfSafe } from '../core/open-external'

const env: Env = realEnv()

declare const __APP_VERSION__: string

function appVersion(): string {
  // app.getVersion() reports Electron's version when running unpackaged, so the value
  // baked in at build time is preferred and the runtime value is only a fallback.
  return typeof __APP_VERSION__ === 'string' ? __APP_VERSION__ : app.getVersion()
}

/** Rejects anything that is not a string array of known component ids. */
function sanitiseComponentIds(input: unknown): string[] {
  if (!Array.isArray(input)) return []
  const known = new Set(COMPONENTS.map((c) => c.id))
  return input.filter((value): value is string => typeof value === 'string' && known.has(value))
}

function sanitiseBackupId(input: unknown): string | null {
  if (typeof input !== 'string') return null
  // Backup ids are generated by this app and always match this shape.
  return /^backup-[0-9TZ-]{10,40}$/.test(input) ? input : null
}

export function registerIpcHandlers(): void {
  ipcMain.handle(CHANNELS.appInfo, (): AppInfo => {
    return {
      version: appVersion(),
      name: 'Better Claude Setup',
      tagline: 'Upgrade Claude into a smarter, more capable assistant in a few minutes.',
      author: 'Made by KC8 — OhTheGreatGitsby',
      disclaimer:
        'Better Claude Setup is an independent community project. It is not affiliated with, endorsed by, or supported by Anthropic.'
    }
  })

  ipcMain.handle(CHANNELS.catalog, () => ({
    categories: CATEGORIES,
    components: COMPONENTS,
    recommended: recommendedComponentIds()
  }))

  ipcMain.handle(CHANNELS.scan, async (event): Promise<DetectionResult> => {
    // Each stage is reported to the window as it genuinely finishes, so the scan screen
    // shows real progress rather than a timed animation.
    return scanSystem(env, appVersion(), (step) => {
      if (!event.sender.isDestroyed()) event.sender.send(CHANNELS.scanProgress, step)
    })
  })

  ipcMain.handle(CHANNELS.plan, async (_event, ids: unknown): Promise<InstallPlan> => {
    return buildPlan(env, appVersion(), sanitiseComponentIds(ids))
  })

  ipcMain.handle(CHANNELS.install, async (event, ids: unknown): Promise<OperationResult> => {
    const componentIds = sanitiseComponentIds(ids)
    await log(env, 'info', `Install requested for ${componentIds.length} components`)
    return installComponents(env, appVersion(), componentIds, (step, done, total) => {
      if (!event.sender.isDestroyed()) {
        event.sender.send(CHANNELS.installProgress, { step, done, total })
      }
    })
  })

  ipcMain.handle(CHANNELS.remove, async (_event, ids: unknown): Promise<OperationResult> => {
    return removeComponents(env, appVersion(), sanitiseComponentIds(ids))
  })

  ipcMain.handle(CHANNELS.backups, async (): Promise<BackupRecord[]> => listBackups(env))

  ipcMain.handle(CHANNELS.restore, async (_event, id: unknown): Promise<OperationResult> => {
    const backupId = sanitiseBackupId(id)
    if (!backupId) {
      return {
        ok: false,
        steps: [],
        backupId: null,
        rolledBack: false,
        summary: 'That restore point could not be identified, so nothing was changed.'
      }
    }
    return restoreFromBackup(env, appVersion(), backupId)
  })

  ipcMain.handle(CHANNELS.installedComponents, async (): Promise<string[]> => {
    const manifest = await loadManifest(env, appVersion())
    return manifest.components.map((c) => c.componentId)
  })

  ipcMain.handle(CHANNELS.claudeCodeRoute, async () => {
    const route = await chooseInstallRoute(env)
    return { route, command: describeRoute(route) }
  })

  ipcMain.handle(CHANNELS.installClaudeCode, async (): Promise<OperationResult> => {
    return installClaudeCode(env)
  })

  ipcMain.handle(CHANNELS.diagnostics, async (): Promise<string> => {
    return buildDiagnosticReport(env, appVersion())
  })

  ipcMain.handle(CHANNELS.saveDiagnostics, async (): Promise<{ saved: boolean; path?: string }> => {
    const report = await buildDiagnosticReport(env, appVersion())
    const result = await dialog.showSaveDialog({
      title: 'Save diagnostic report',
      defaultPath: join(app.getPath('documents'), 'better-claude-setup-diagnostics.md'),
      filters: [{ name: 'Markdown', extensions: ['md'] }]
    })
    if (result.canceled || !result.filePath) return { saved: false }
    await fs.writeFile(result.filePath, report, 'utf8')
    return { saved: true, path: result.filePath }
  })

  // ---- Claude account skills -------------------------------------------------------
  // None of these touch the user's Claude account. They build upload packages from local
  // content, open a folder, and record what the user tells us they did.

  ipcMain.handle(CHANNELS.chatSkillsState, async (): Promise<ChatSkillsState> => {
    const manifest = await loadManifest(env, appVersion())
    return readChatSkillsState(
      env,
      manifest.components.map((c) => c.componentId)
    )
  })

  ipcMain.handle(
    CHANNELS.chatSkillsPrepare,
    async (): Promise<{ directory: string; files: string[] }> => {
      const manifest = await loadManifest(env, appVersion())
      const skillIds = chatSkillIdsFor(manifest.components.map((c) => c.componentId))
      const built = await buildChatPackages(env, skillIds)
      await log(env, 'info', `Prepared ${built.files.length} chat skill packages`)
      return built
    }
  )

  ipcMain.handle(CHANNELS.chatSkillsConfirm, async (): Promise<ChatSkillsState> => {
    const manifest = await loadManifest(env, appVersion())
    const componentIds = manifest.components.map((c) => c.componentId)
    await confirmChatSetup(env, chatSkillIdsFor(componentIds))
    return readChatSkillsState(env, componentIds)
  })

  ipcMain.handle(CHANNELS.chatSkillsReset, async (): Promise<ChatSkillsState> => {
    const manifest = await loadManifest(env, appVersion())
    const componentIds = manifest.components.map((c) => c.componentId)
    await clearChatSetup(env)
    return readChatSkillsState(env, componentIds)
  })

  ipcMain.handle(CHANNELS.chatSkillsReveal, async (): Promise<boolean> => {
    try {
      await shell.openPath(chatPackageDir(env))
      return true
    } catch {
      return false
    }
  })

  ipcMain.handle(CHANNELS.openExternal, async (_event, url: unknown): Promise<boolean> => {
    if (typeof url !== 'string') return false
    return openExternalIfSafe(url)
  })

  ipcMain.handle(CHANNELS.revealConfig, async (_event, which: unknown): Promise<boolean> => {
    const target = which === 'backups' ? appStateDir(env) : claudeHome(env)
    try {
      await shell.openPath(target)
      return true
    } catch {
      return false
    }
  })
}
